name: TOC Generator
on:
  push:
    paths:
      - 'README.md'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
